services:
  dw-client:
    image: node:18.20.1-slim
    labels:
      traefik.http.routers.dw-translations.rule: "Host(`dw-translations.local`)"
      traefik.http.routers.dw-translations.tls: "true"
      traefik.http.services.dw-translations.loadbalancer.server.port: "3002"
      traefik.docker.network: "reverse_proxy"
    working_dir: /app
    user: node
    networks:
      - reverse_proxy
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: unless-stopped
    command: sh -c "cd client && npm start"
    ports:
      - "3000:3000"
  dw-server:
    image: node:18.20.1-slim
    labels:
      traefik.enable: "false"
    working_dir: /app
    user: node
    ports:
      - "3001:3001"
    networks:
      - reverse_proxy
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: unless-stopped
    command: sh -c "cd server && npm run start:dev"
  dw-database:
    image: "postgres:11"
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_USER: ${DW_DATABASE_USER}
      POSTGRES_PASSWORD: ${DW_DATABASE_PASSWORD}
      POSTGRES_DB: ${DW_DATABASE_DB}
      PGPORT: 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DW_DATABASE_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DW_DATABASE_PORT}:5433"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

volumes:
  database-data: